### PR TITLE
😥 [DO NOT MERGE] Correct default features key.

### PR DESCRIPTION
**Pull request by psbrandt**
As a Rust newbie, this had me scratching my head for a good long while.

### CODE REVIEW

**Comment by psbrandt** [comment]
This change brings to light another problem: rust-lang/rust#44113 (`global_allocator` cannot be used in submodules). To fix this in my project I just dumped the `cfg_if` macro in `lib.rs`, but I'm not sure what you want for the template.

p.s. I ran into this while working through the Game of Life tutorial.

**Comment by fitzgen** [comment]
Thanks for sending a PR! I was just alerted to this the other day, and hadn't made a fix yet. I'll do a PR for everything in a second :)

**Comment by psbrandt** [comment]
No problem. Sorry I didn't implement the complete fix.

**Comment by fitzgen** [comment]
Closing in favor or #25 -- thanks again!

**Pull request closed without merging**
