### PR TITLE
edition = "2018"

### PR DESCRIPTION
**Pull request by not-fl3**

### CODE REVIEW

**Review by ashleygwilliams — APPROVED** [review]
lgtm! thanks so much!

**Comment by ThatNerdyPikachu** [comment]
Are we gonna merge this?

**Comment by ThatNerdyPikachu** [comment]
Is this going to get merged?

**Comment by luojia65** [comment]
Is this going to get merged?

**Comment by vlad20012** [comment]
It's now 2018, so the PR can be closed

**Pull request closed without merging**
